experiment: "celeba64_comp"

data:
  train: '../data/to-ml-celeba/train'
  validate: '../data/to-ml-celeba/test'
  test: '../data/to-ml-celeba/test'
  name: 'CelebA64'
  seed: 0
  range_data: 80000

batch_size: 256

net:
  name: 'CNNGated'
  zk: 16
  k: 16
  sdim: 2
  ichan:
    - 3
    - 32
    - 32
    - 64
    - 64
    - 128
    - 128
    - 256
    - 256
  learning_rate: 0.0004
  sigma: 1.0
  ncode: 8
  cout: 100
  embed_dim: 8

pmodel:
  name: 'PixelCNN'
  learning_rate: 0.001
  channels: 64
  ncode: 8
  depth: 4
  kernel: 5
  residual: 0.1

loss:
  name: 'DiscMixLogisticLoss'

ploss:
  name: 'CECondLoss'

device: 'cuda'
n_epochs: 400
method: 'compression'
nclass_outcome: 10
gamma: 0.0
nclass_sensitive: 2
annealing_epochs: 400
warmup_epochs: 10
lr_min: 0.00004

#run: 'checkpoints/mnist_rot_comp_cnn_test/epoch_19'
#prun: 'checkpoints/mnist_rot_comp_cnn_test/pmodel_epoch_19'
