autoencoder: 'configs/celeba64/celeba_comp_cnn.yml'

probes_list:
  - 'configs/probes/multi_width_256_depth_4.yml'

task_list:
  - 'configs/probes/multi_width_256_depth_4.yml'

decode: False

experiment_type: 'predict_outcome_sensitive'

seed: 0

name: 'celeba_comp_test'

noisy: False

logging_dir: '/scratch/xgitiaux/fals'

checkpoints: '/scratch/xgitiaux/fals/checkpoints'