experiment: "celeba64_comp"

data:
  train: '../data/to-ml-celeba/train'
  validate: '../data/to-ml-celeba/test'
  test: '../data/to-ml-celeba/test'
  name: 'CelebA64'
  seed: 0
  range_data: 40000

batch_size: 256

net:
  name: 'CNNQuant'
  zk: 16
  k: 16
  sdim: 2
  ichan:
    - 3
    - 32
    - 64
    - 128
    - 256
    - 256
  learning_rate: 0.0001
  ncode: 100
  cout: 3
  dim: 8
  embed_dim: 64

pmodel:
  name: 'PixelCNN'
  learning_rate: 0.001
  channels: 64
  channels_in: 64
  ncode: 512
  depth: 4
  kernel: 5
  residual: 0.1

loss:
  name: 'L2Loss' #'DiscMixLogisticLoss'

ploss:
  name: 'CECondLoss'

device: 'cuda'
n_epochs: 800
method: 'compression'
nclass_outcome: 10
gamma: 0.0
nclass_sensitive: 2
annealing_epochs: 400
warmup_epochs: 10
lr_min: 0.00004

#run: '/scratch/xgitiaux/afbc/checkpoints/celeba_comp_test/epoch_399'
#prun: '/scratch/xgitiaux/afbc/checkpoints/celeba_comp_test/epoch_399'
