autoencoder: 'configs/mnist_rot/mnist_comp_cnn.yml'

probes_list:
  - 'configs/probes/multi_width_256_depth_4.yml'

task_list:
  - 'configs/probes/multi_width_256_depth_4.yml'

decode: False

experiment_type: 'predict_outcome_sensitive'

seed: 0

name: 'mnist_rot_comp_cnn_all'

noisy: False

logging_dir: '/scratch/xgitiaux/afbc'

checkpoints: '/scratch/xgitiaux/afbc/checkpoints'