experiment: "mnist_rot_comp"

data:
  train: '../data/mnist-rot/training.pt'
  validate: '../data/mnist-rot/training.pt'
  test: '../data/mnist-rot/test.pt'
  name: 'BinarizedMNISTRot'
  seed: 0
  range_data: 10000
  reshape: False

batch_size: 128

net:
  name: 'CNNGated'
  zk: 4
  k: 8
  sdim: 5
  ichan:
    - 1
    - 32
    - 64
    - 128
    - 256
  learning_rate: 0.001
  sigma: 0.5
  ncode: 3

pmodel:
  name: 'PixelCNN'
  learning_rate: 0.001
  channels: 48
  ncode: 3
  depth: 2
  nclass: 5
  kernel: 5

loss:
  name: 'BernouilliLoss'

ploss:
  name: 'CECondLoss'

device: 'cuda'
n_epochs: 400
method: 'compression'
nclass_outcome: 10
gamma: 0.0
nclass_sensitive: 5
annealing_epochs: 100
warmup_epochs: 10
lr_min: 0.00001

#run: 'checkpoints/mnist_rot_comp_cnn_test/epoch_399'
#prun: 'checkpoints/mnist_rot_comp_cnn_test/pmodel_epoch_399'
